### ISSUE TITLE
404 not founded and a ERROR

### ISSUE THREAD

**Issue by Saferman** [shlee89/athena#1]
Hi, your athena's onos-setup-ubuntu-devenv has a 404 problem:
wget http://download.nextag.com/apache/karaf/3.0.5/apache-karaf-3.0.5.tar.gz
The website doesn't have 3.0.5 version. Finally, I use 3.0.9 instead

Also, I encounter a error when executing a command :mvn clean install:
org.onosproject.athena.database.impl.FeatureDatabaseManagerTest-output.txt
TEST-org.onosproject.athena.database.impl.FeatureDatabaseManagerTest.xml
I didn't pass this test and can you help me out?

Looking forward to your reply

**Comment by shlee89** [comment]
Hello Saferman, 
We have not implemented test functions. You can build with "mvn clean install -DskipTests", which builds whole without running test functions.

Sorry for late.
