### ISSUE TITLE
run single mode error

### ISSUE THREAD

**Issue by why1988seu** [shlee89/athena#3]
(1)when I run the "onos-karaf clean", it says that "command not found"
(2)when I run the1"ONOS> app activate org.onosproject.framework" command, it says that "No such org.onosproject.framework"

**Comment by shlee89** [comment]
You might misconfigure the Athena framework. I recommend you to follow the instructions on the main page before initiating the Athena instance.

**Comment by why1988seu** [comment]
Thank you. When I run the "maven install clean", it can't download "https://cdn.rawgit.com/opennetworkinglab/onos-bmv2/8f675d0284e9e014f1b8ed502ba54e61d68108cf/thrift_src/standard.thrift
". But I can use wget to download that file, how can I solve this?

**Comment by shlee89** [comment]
Could you post the screenshot?

**Comment by why1988seu** [comment]
I build the athena success. But when I run the "onos-karaf clean", it still says that "command not found".  Where can I find the onos-karaf command？

**Comment by why1988seu** [comment]
(1)I build the athena success. But when I run the "onos-karaf clean", it still says that "command not found". Where can I find the onos-karaf command？
(2)when I run the "app activate org.onosproject.framework", it says that "No such application: org.onosproject.framework"

**Comment by shlee89** [comment]
Did you execute following commands "source ./athena-config-env-single" and "source ./tools/dev/bash_profile"?

**Comment by why1988seu** [comment]
My ONOS is in the "/opt/onos-1.6.0", so is the "apache-karaf-3.0.5"

**Comment by why1988seu** [comment]
My ONOS is in the "/opt/onos-1.6.0", so is the "apache-karaf-3.0.5". How to modify the the program?

**Comment by shlee89** [comment]
How about following the instructions? I don`t understand why the ONOS is over there.
What program? Please give me details.

**Comment by shlee89** [comment]
I will close the issue. If you did not resolve the problem properly, please leave me another issue.
