### ISSUE TITLE
[Suggestion] Make a simple DDoS detection/prevention app

### ISSUE THREAD

**Issue by lyndon160** [shlee89/athena#4]
The learning curve for someone wanting to create their own app is very intimidating. 

Your main user application seems to include a lot of different solutions in one. It's nearly 2000 lines long!

Or is your system purely and solely designed to defend against DDoS and user application development isn't an aim?

I see the "sample" user application but that doesn't seem to do anything on its own. Do you have an example of a simple DDoS application available so that others can learn how?

**Comment by shlee89** [comment]
Thank you for your valuable comments. 
I really hope to provide more readable and easy-to-follow tutorials to potential users. However, I don't have enough time for that now. Thus, as I got questions about Athena, I have tried to reply to the answers as soon as possible.
Anyone interested in that would be great to improve the Athena framework.
Thanks
